name: nix-build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-nix-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    # Later, we can use Cachix or similar to distribute the binaries automatically.
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: |
        nix build \
          -L \
          --no-link \
          '.#bin'
    - run: |
        nix build \
          -L \
          -o ./imgTarball \
          '.#ociImg'
