name: tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - name: Setup Clojure tools
        uses: DeLaGuardo/setup-clojure@master
        with:
          bb: 0.8.2
          tools-deps: 1.10.3.1040
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install ws
        run: npm install ws
      - name: Cache m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}
      - name: Cache gitlibs
        uses: actions/cache@v2
        with:
          path: ~/.gitlibs
          key: gitlibs-${{ hashFiles('deps.edn') }}
      - name: Prepare dependencies
        run: clojure -P -M:test:clj-test:cljs-test
      - name: Run Clojure tests
        run: bb test:clj
      - name: Run ClojureScript tests
        run: bb test:cljs
